# 5層ハイブリッドLLMシステム設定 (拡張版)
# Tier0 (最優先) -> Tier3 (最高品質) の順序で定義
# 注意: OpenRouterモデルは別途openrouter-models.yamlから動的に読み込まれます

models:
  # 従来モデル定義（後方互換性のため残存）
  # OpenRouter Registry導入により、これらは補完的に使用されます
  
  # Tier 0: 無料コーディング特化モデル（最高優先度）
  qwen3_coder_free:
    id: qwen3_coder_free
    name: qwen/qwen3-coder:free  # OpenRouter無料枠
    provider: openrouter
    tier: 0
    cost_per_1k_tokens:
      input: 0.00   # 完全無料
      output: 0.00  # 完全無料
    latency_ms: 300
    max_tokens: 4096
    capabilities:
      - coding
      - debugging
      - code_review
      - refactoring
    languages:
      - python
      - javascript
      - typescript
      - java
      - cpp
      - rust
      - go
    priority_keywords:
      - "コード"
      - "関数"
      - "実装"
      - "プログラム"
      - "スクリプト"
      - "バグ修正"
      - "リファクタリング"
      - "code"
      - "function"
      - "implement"
      - "script"
      - "debug"
    rate_limits:
      requests_per_minute: 20
      daily_limit: 200
    api_client: OpenRouterAPIClient

  # Tier 0: Gemini 2.5 Pro Exp - 最高性能・実験版・無料（実装実験中のため課金されない）
  gemini_2_5_pro_exp:
    id: gemini_2_5_pro_exp
    name: gemini:experimental  # エイリアス使用: gemini-2.5-pro-002
    provider: google
    tier: 0
    cost_per_1k_tokens:
      input: 0.00   # 実験版のため無料
      output: 0.00  # 実験版のため無料
    latency_ms: 400
    max_tokens: 8192
    capabilities:
      - advanced_reasoning
      - complex_analysis
      - architectural_design
      - technical_writing
      - code_generation
      - performance_optimization
      - high_quality_generation
    priority_keywords:
      - "複雑"
      - "アーキテクチャ"
      - "高度"
      - "分析"
      - "設計"
      - "complex"
      - "advanced"
      - "architecture"
      - "design"
      - "analysis"
      - "reasoning"
    api_client: GeminiAPIClient

  # Tier 1: 汎用・高速モデル
  gemini_2_5_flash:
    id: gemini_2_5_flash
    name: gemini-2.5-flash  # Gemini 2.5 Flash最新版
    provider: google
    tier: 1
    cost_per_1k_tokens:
      input: 0.075  # $0.075/1K入力トークン
      output: 0.30  # $0.30/1K出力トークン
    latency_ms: 400
    max_tokens: 8192
    capabilities:
      - general_inquiry
      - validation
      - summarization
      - translation
      - analysis
      - fast_processing
    priority_keywords:
      - "調査"
      - "検証"
      - "要約"
      - "翻訳"
      - "分析"
      - "research"
      - "validate"
      - "summarize"
      - "translate"
    api_client: GeminiAPIClient

  # Tier 2: Claude Sonnet 4 - 複雑推論・統合判断・最高性能メインモデル (Anthropic直接API)
  claude_sonnet:
    id: claude_sonnet
    name: claude-sonnet-4-20250514  # Claude Sonnet 4最新版 (Anthropic直接API)
    provider: anthropic
    tier: 2
    cost_per_1k_tokens:
      input: 3.00   # $3.00/1K入力トークン
      output: 15.00 # $15.00/1K出力トークン
    latency_ms: 800
    max_tokens: 64000  # Claude 4の大容量出力対応
    capabilities:
      - complex_reasoning
      - integration
      - architectural_design
      - technical_writing
      - code_review
      - general_tasks
      - advanced_coding
      - extended_thinking
      - memory_management
    priority_keywords:
      - "設計"
      - "アーキテクチャ"
      - "複雑"
      - "統合"
      - "design"
      - "architecture"
      - "complex"
      - "integration"
      - "reasoning"
    api_client: AnthropicAPIClient

  # Tier 3: GPT-4o/Gemini Pro - 最高品質設計判断
  gpt4o:
    id: gpt4o
    name: gpt:stable  # エイリアス使用: gpt-4o-2024-08-06
    provider: openai
    tier: 3
    cost_per_1k_tokens:
      input: 2.50   # $2.50/1K入力トークン
      output: 10.00 # $10.00/1K出力トークン
    latency_ms: 1500
    max_tokens: 4096
    capabilities:
      - premium_analysis
      - strategic_planning
      - high_quality_generation
      - critical_decisions
    priority_keywords:
      - "戦略"
      - "重要"
      - "最高品質"
      - "critical"
      - "strategic"
      - "premium"
    api_client: OpenAIAPIClient

  gemini_pro:
    id: gemini_pro
    name: gemini:stable  # エイリアス使用: gemini-1.5-pro-002
    provider: google
    tier: 3
    cost_per_1k_tokens:
      input: 1.25   # $1.25/1K入力トークン
      output: 5.00  # $5.00/1K出力トークン
    latency_ms: 1200
    max_tokens: 8192
    capabilities:
      - premium_analysis
      - multimodal_processing
      - strategic_planning
      - high_quality_generation
    priority_keywords:
      - "戦略"
      - "画像解析"
      - "マルチモーダル"
      - "strategic"
      - "multimodal"
      - "image"
    api_client: GeminiAPIClient

  # Tier 4: GPT-5 - 最高級推論・戦略判断・制限付き使用 (高コスト)
  gpt5:
    id: gpt5
    name: gpt-5  # OpenAI 直接API
    provider: openai
    tier: 4  # 新設：最高級Tier
    cost_per_1k_tokens:
      input: 30.00   # $30.00/1K入力トークン（推定高コスト）
      output: 60.00  # $60.00/1K出力トークン（推定高コスト）
    latency_ms: 3000  # 推理モデルのため高レイテンシ
    max_tokens: 16384  # 大容量出力対応
    capabilities:
      - ultimate_reasoning      # 最高レベル推論
      - strategic_architecture  # 戦略的アーキテクチャ設計
      - critical_analysis       # 重要判断支援
      - complex_problem_solving # 複雑問題解決
      - enterprise_planning     # 企業レベル計画立案
      - risk_assessment         # リスク評価
      - innovation_strategy     # イノベーション戦略
    priority_keywords:
      - "戦略計画"
      - "重要判断" 
      - "リスク評価"
      - "最重要"
      - "enterprise"
      - "strategic plan"
      - "critical decision"
      - "risk assessment"
      - "mission critical"
      - "ultimate"
      - "comprehensive"
    usage_restrictions:
      max_daily_requests: 5      # 1日最大5回
      max_hourly_requests: 2     # 1時間最大2回
      cooldown_minutes: 30       # 30分クールダウン
      approval_required: true    # 手動承認必須
      business_hours_only: true  # 営業時間のみ
      max_request_cost_usd: 50.00  # 単一リクエスト最大$50
    api_client: OpenAIAPIClient

  # Tier 4: GPT-5 Mini - GPT-5の軽量版・やや制限緩和 (中高コスト)
  gpt5_mini:
    id: gpt5_mini
    name: gpt-5-mini  # OpenAI 直接API
    provider: openai
    tier: 4
    cost_per_1k_tokens:
      input: 15.00   # $15.00/1K入力トークン（GPT-5の半額）
      output: 30.00  # $30.00/1K出力トークン（GPT-5の半額）
    latency_ms: 2000  # GPT-5より高速
    max_tokens: 8192   # やや制限
    capabilities:
      - advanced_reasoning      # 高度推論
      - strategic_analysis      # 戦略分析
      - complex_problem_solving # 複雑問題解決
      - architectural_guidance  # アーキテクチャ指導
      - optimization_strategy   # 最適化戦略
    priority_keywords:
      - "戦略分析"
      - "最適化"
      - "高度分析"
      - "strategic analysis"
      - "optimization"
      - "advanced analysis"
      - "guidance"
    usage_restrictions:
      max_daily_requests: 10     # 1日最大10回
      max_hourly_requests: 3     # 1時間最大3回
      cooldown_minutes: 15       # 15分クールダウン
      approval_required: false   # 自動承認
      business_hours_only: false # 24時間利用可能
      max_request_cost_usd: 25.00  # 単一リクエスト最大$25
    api_client: OpenAIAPIClient

# ルーティング設定
routing:
  default_tier: 1  # デフォルトはTier1から開始
  fallback_enabled: true
  max_retries: 3
  timeout_ms: 30000

  # タスク分類ルール（Gemini 2.5 Pro Expを優先）
  task_classification:
    experimental_priority:
      keywords: ["複雑", "アーキテクチャ", "高度", "分析", "設計", "complex", "advanced", "architecture", "design", "analysis", "reasoning"]
      preferred_tier: 0  # Gemini 2.5 Pro Exp優先
    coding:
      keywords: ["code", "コード", "function", "関数", "implement", "実装", "script", "スクリプト", "debug", "デバッグ", "program", "プログラム"]
      preferred_tier: 0  # OpenRouter Qwen との併用
    general:
      keywords: ["explain", "説明", "what", "何", "how", "どう", "why", "なぜ"]
      preferred_tier: 1
    complex_analysis:
      keywords: ["analyze", "分析", "design", "設計", "architecture", "アーキテクチャ", "strategy", "戦略"]
      preferred_tier: 0  # Gemini 2.5 Pro Exp優先にシフト
    premium:
      keywords: ["critical", "重要", "strategic", "戦略的", "premium", "最高品質"]
      preferred_tier: 3
    ultimate:
      keywords: ["戦略計画", "重要判断", "リスク評価", "最重要", "enterprise", "strategic plan", "critical decision", "risk assessment", "mission critical", "ultimate", "comprehensive"]
      preferred_tier: 4

# 協調メカニズム設定
collaboration:
  cascade_enabled: false     # フォールバック機能（Gemini性能評価用に無効化）
  refinement_enabled: false  # 上位Tierでの改善（Gemini性能評価用に無効化）
  parallel_enabled: false    # 並列処理（リソース消費大）
  
  quality_thresholds:
    min_response_length: 10
    max_error_rate: 0.1
    min_confidence_score: 0.7

# コスト管理
cost_management:
  monthly_budget_usd: 70.0   # 月間予算
  tier0_allocation: 0.05     # 5% - 無料枠（Qwen3 Coder Free、Gemini 2.5 Pro Exp）
  tier1_allocation: 0.25     # 25% - 中コストモデル（Gemini 2.5 Flash）
  tier2_allocation: 0.50     # 50% - Claude Sonnet 4（メインモデル）
  tier3_allocation: 0.15     # 15% - Premium models（GPT-4o、Gemini Pro）
  tier4_allocation: 0.05     # 5% - Ultimate models（GPT-5）※厳格制限
  
  # GPT-5専用高コスト制限
  premium_model_restrictions:
    max_daily_requests: 10     # GPT-5系：1日最大10回
    max_hourly_requests: 3     # GPT-5系：1時間最大3回
    max_request_cost_usd: 50.00 # 単一リクエスト最大$50
    daily_budget_allocation: 20  # 日次予算の20%まで
    monthly_budget_allocation: 15 # 月次予算の15%まで
    cooldown_minutes: 15       # 15分クールダウン
    restricted_models:         # 制限対象モデル一覧
      - "gpt5"
      - "gpt5_mini"
    approval_required: false   # 自動承認（コスト制限で制御）
    business_hours_only: false # 24時間利用可能
    business_hours:
      start: "09:00"
      end: "18:00" 
      timezone: "Asia/Tokyo"
      weekdays_only: false
  
  cost_alerts:
    warning_threshold: 0.8   # 80%で警告
    critical_threshold: 0.95 # 95%で制限

# データ保護・情報漏洩防止設定
data_protection:
  # 機微情報保護の基本設定
  confidential_data_handling: true
  
  # プロバイダー別自己学習防止設定
  provider_settings:
    openai:
      store: false                    # 会話履歴保存無効
      training_opt_out: true          # 学習データ使用無効
      data_protection_headers: true   # 保護ヘッダー有効
    
    anthropic:
      training_data_usage: false      # 学習データ使用無効
      data_retention_policy: "no_retention"  # データ保持無効
      anonymous_requests: true        # リクエスト匿名化
    
    google:
      learning_disabled: true         # 学習機能無効
      data_export_disabled: true     # データエクスポート無効
      confidentiality_instruction: true  # 機密性指示
    
    openrouter:
      training_opt_out: true          # 学習データ使用無効
      data_protection_headers: true   # 保護ヘッダー有効
      privacy_mode: "maximum"         # 最大プライバシー設定

  # ログ・監査設定
  audit_settings:
    log_sensitive_requests: false    # 機微リクエストのログ無効
    anonymize_user_data: true       # ユーザーデータ匿名化
    secure_transmission: true       # 安全な送信
    
  # コンプライアンス設定
  compliance:
    gdpr_compliant: true            # GDPR準拠
    hipaa_compliant: true           # HIPAA準拠（該当する場合）
    data_residency: "user_controlled"  # データ保存場所制御

# 外部API層設定
external_apis:
  weather:
    provider: openweathermap
    cost_per_request: 0.001
  stock:
    provider: alpha_vantage
    cost_per_request: 0.005
  news:
    provider: newsapi
    cost_per_request: 0.002